### PR TITLE
trim whitespace from aws signature

### PR DESCRIPTION
**Pull request by revmischa**
This is causing an error because of trailing whitespace on the AWS signature. New versions of urllib2 complain with "Invalid header value"

### CODE REVIEW

**Comment by mbrossard** [comment]
It seems you're trying to fix the issue I reported in #33. I submitted functionally the same patch (#34), but I think my version is better for the RPM packaging. I left the module version at 1.0.1, but increased the version reflected in the RPM package from 1.0 to 1.0.1.

The rpm target in make now builds yum-plugin-s3-iam-1.0.1-1.noarch.rpm (instead of yum-plugin-s3-iam-1.0-1.noarch.rpm earlier).

**Comment by revmischa** [comment]
why not increase the module version too?

**Comment by mbrossard** [comment]
I don't know that yum (or any software for that matters) actually uses the version number from the python module.

The RPM package version information needs to be increased (version or release) so that ```rpm -U``` or ```yum update``` works. I also think the module version and the rpm version should match, which is not the case in master or your patch.

**Comment by asedge** [comment]
This project needs a new maintainer, see: https://github.com/seporaitis/yum-s3-iam/issues/38 if interested in discussing further.

**Comment by mbrossard** [comment]
@revmischa: I merged #34.

Do you think we should update the version number again?

**Pull request closed without merging**
